# Generated by Django 4.2 on 2024-07-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomador_Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_fijo', models.IntegerField()),
                ('movil', models.IntegerField()),
                ('localizacion', models.TextField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentes.agentes')),
            ],
        ),
        migrations.CreateModel(
            name='Tomadores',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100)),
                ('direcc', models.CharField(max_length=200)),
                ('agentes', models.ManyToManyField(related_name='tomadores', through='tomadores.Tomador_Agente', to='agentes.agentes')),
            ],
        ),
        migrations.AddField(
            model_name='tomador_agente',
            name='tomador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomadores.tomadores'),
        ),
    ]
