# Generated by Django 4.2 on 2024-07-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomadores',
            name='agentes',
        ),
    ]
