# Generated by Django 4.2 on 2024-07-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomadores', '0002_remove_tomadores_agentes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tomador_Agente',
        ),
    ]
