# Generated by Django 4.2 on 2024-07-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomadores', '0003_delete_tomador_agente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomadores',
            name='direcc',
        ),
    ]
