# Generated by Django 4.2 on 2024-07-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomadores', '0003_delete_tomador_agente'),
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomador_Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_fijo', models.IntegerField()),
                ('movil', models.IntegerField()),
                ('localizacion', models.TextField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentes.agentes')),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomadores.tomadores')),
            ],
        ),
        migrations.AddField(
            model_name='agentes',
            name='tomadores',
            field=models.ManyToManyField(through='agentes.Tomador_Agente', to='tomadores.tomadores'),
        ),
    ]
