# Generated by Django 4.2 on 2024-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_tomador_agente_agentes_tomadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomador_agente',
            name='direcc',
            field=models.CharField(default='Madruga', max_length=200),
        ),
    ]
