# Generated by Django 4.2 on 2024-07-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0003_tomador_agente_direcc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomador_agente',
            name='direcc',
            field=models.CharField(max_length=200),
        ),
    ]
