# Generated by Django 4.2 on 2024-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0005_tomador_agente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomador_agente',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
