# Generated by Django 4.2 on 2024-07-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0006_alter_tomador_agente_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomador_agente',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.AddField(
            model_name='tomador_agente',
            name='fecha_modificacion',
            field=models.DateTimeField(default='2024-07-10T18:25:05.5478'),
        ),
    ]
