# Generated by Django 4.2 on 2024-07-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0007_rename_fecha_tomador_agente_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomador_agente',
            name='fecha_modificacion',
            field=models.DateTimeField(),
        ),
    ]
