# Generated by Django 4.2 on 2024-07-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('no_poliza', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('periodo_pago', models.IntegerField()),
            ],
        ),
    ]
