# Generated by Django 4.2 on 2024-07-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_descuentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='porcenntaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reglasaños',
            name='porcentaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reglasaños',
            name='rango_años',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tiposoficios',
            name='costo_diario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tiposoficios',
            name='porcenntaje',
            field=models.FloatField(),
        ),
    ]
