# Generated by Django 4.2 on 2024-07-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0001_initial'),
        ('agentes', '0008_alter_tomador_agente_fecha_modificacion'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='seguros',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguros.seguros'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='tomadores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agentes.tomador_agente'),
        ),
    ]
