# Generated by Django 4.2 on 2024-07-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contratos_seguros_alter_contratos_tomadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='valor_incapacidad_permanente',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_incapacidad_temporal',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_muerte',
            field=models.IntegerField(default=9),
        ),
    ]
