# Generated by Django 4.2 on 2024-07-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contratos_valor_incapacidad_permanente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='tipo_oficio',
            field=models.IntegerField(default=9),
        ),
    ]
