# Generated by Django 4.2 on 2024-07-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contratos_tipo_oficio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglasAños',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rango_años', models.IntegerField()),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposOficios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('porcenntaje', models.IntegerField()),
                ('costo_diario', models.IntegerField()),
            ],
        ),
    ]
